export enum GIInfoType {
  INVALID,
  FUNCTION,
  CALLBACK,
  STRUCT,
  BOXED,
  ENUM,
  FLAGS,
  OBJECT,
  INTERFACE,
  CONSTANT,
  INVALID_0,
  UNION,
  VALUE,
  SIGNAL,
  VFUNC,
  PROPERTY,
  FIELD,
  ARG,
  TYPE,
  UNRESOLVED,
}

export enum GIDirection {
  IN,
  OUT,
  INOUT,
}

export enum GITypeTag {
  VOID,
  BOOLEAN,
  INT8,
  UINT8,
  INT16,
  UINT16,
  INT32,
  UINT32,
  INT64,
  UINT64,
  FLOAT,
  DOUBLE,
  GTYPE,
  UTF8,
  FILENAME,
  ARRAY,
  INTERFACE,
  GLIST,
  GSLIST,
  GHASH,
  ERROR,
  UNICHAR,
}

export enum GIArrayType {
  C,
  ARRAY,
  PTR_ARRAY,
  BYTE_ARRAY,
}

export enum GIFunctionInfoFlags {
  IS_METHOD = 1 << 0,
  IS_CONSTRUCTOR = 1 << 1,
  IS_GETTER = 1 << 2,
  IS_SETTER = 1 << 3,
  WRAPS_VFUNC = 1 << 4,
  THROWS = 1 << 5,
}

export enum GInvokeError {
  FAILED,
  SYMBOL_NOT_FOUND,
  ARGUMENT_MISMATCH,
}

export enum GIRepositoryLoadFlags {
  LAZY,
}

export enum GIRepositoryError {
  TYPELIB_NOT_FOUND,
  NAMESPACE_MISMATCH,
  NAMESPACE_VERSION_CONFLICT,
  LIBRARY_NOT_FOUND,
}

export enum GParamFlags {
  READABLE = 1 << 0,
  WRITABLE = 1 << 1,
  READWRITE = READABLE | WRITABLE,
  CONSTRUCT = 1 << 2,
  CONSTRUCT_ONLY = 1 << 3,
  LAX_VALIDATION = 1 << 4,
  STATIC_NAME = 1 << 5,
  STATIC_NICK = 1 << 6,
  STATIC_BLURB = 1 << 7,
  EXPLICIT_NOTIFY = 1 << 30,
  DEPRECATED = 1 << 31,
}

export const GFieldInfoFlags = {
  READABLE: 1 << 0,
  WRITABLE: 1 << 1,
};

export const GConnectFlags = {
  AFTER: 1 << 0,
  SWAPPED: 1 << 1,
};

export const G_TYPE_FUNDAMENTAL_SHIFT = 2;
export const G_TYPE_FUNDAMENTAL_MAX = 255 << G_TYPE_FUNDAMENTAL_SHIFT;

export enum GType {
  INVALID = (0 << G_TYPE_FUNDAMENTAL_SHIFT),
  NONE = (1 << G_TYPE_FUNDAMENTAL_SHIFT),
  INTERFACE = (2 << G_TYPE_FUNDAMENTAL_SHIFT),
  CHAR = (3 << G_TYPE_FUNDAMENTAL_SHIFT),
  UCHAR = (4 << G_TYPE_FUNDAMENTAL_SHIFT),
  BOOLEAN = (5 << G_TYPE_FUNDAMENTAL_SHIFT),
  INT = (6 << G_TYPE_FUNDAMENTAL_SHIFT),
  UINT = (7 << G_TYPE_FUNDAMENTAL_SHIFT),
  LONG = (8 << G_TYPE_FUNDAMENTAL_SHIFT),
  ULONG = (9 << G_TYPE_FUNDAMENTAL_SHIFT),
  INT64 = (10 << G_TYPE_FUNDAMENTAL_SHIFT),
  UINT64 = (11 << G_TYPE_FUNDAMENTAL_SHIFT),
  ENUM = (12 << G_TYPE_FUNDAMENTAL_SHIFT),
  FLAGS = (13 << G_TYPE_FUNDAMENTAL_SHIFT),
  FLOAT = (14 << G_TYPE_FUNDAMENTAL_SHIFT),
  DOUBLE = (15 << G_TYPE_FUNDAMENTAL_SHIFT),
  STRING = (16 << G_TYPE_FUNDAMENTAL_SHIFT),
  POINTER = (17 << G_TYPE_FUNDAMENTAL_SHIFT),
  BOXED = (18 << G_TYPE_FUNDAMENTAL_SHIFT),
  PARAM = (19 << G_TYPE_FUNDAMENTAL_SHIFT),
  OBJECT = (20 << G_TYPE_FUNDAMENTAL_SHIFT),
  VARIANT = (21 << G_TYPE_FUNDAMENTAL_SHIFT),
}
