export const GIInfoType = {
  INVALID: 0,
  FUNCTION: 1,
  CALLBACK: 2,
  STRUCT: 3,
  BOXED: 4,
  ENUM: 5,
  FLAGS: 6,
  OBJECT: 7,
  INTERFACE: 8,
  CONSTANT: 9,
  INVALID_0: 10,
  UNION: 11,
  VALUE: 12,
  SIGNAL: 13,
  VFUNC: 14,
  PROPERTY: 15,
  FIELD: 16,
  ARG: 17,
  TYPE: 18,
  UNRESOLVED: 19,
};

export const GIDirection = {
  IN: 0,
  OUT: 1,
  INOUT: 2,
};

export const GITypeTag = {
  VOID: 0,
  BOOLEAN: 1,
  INT8: 2,
  UINT8: 3,
  INT16: 4,
  UINT16: 5,
  INT32: 6,
  UINT32: 7,
  INT64: 8,
  UINT64: 9,
  FLOAT: 10,
  DOUBLE: 11,
  GTYPE: 12,
  UTF8: 13,
  FILENAME: 14,
  ARRAY: 15,
  INTERFACE: 16,
  GLIST: 17,
  GSLIST: 18,
  GHASH: 19,
  ERROR: 20,
  UNICHAR: 21,
};

export const GIArrayType = {
  C: 0,
  ARRAY: 1,
  PTR_ARRAY: 2,
  BYTE_ARRAY: 3,
};

export const GIFunctionInfoFlags = {
  IS_METHOD: 1,
  IS_CONSTRUCTOR: 2,
  IS_GETTER: 4,
  IS_SETTER: 8,
  WRAPS_VFUNC: 16,
  THROWS: 32,
};

export const GInvokeError = {
  FAILED: 0,
  SYMBOL_NOT_FOUND: 1,
  ARGUMENT_MISMATCH: 2,
};

export const GIRepositoryLoadFlags = {
  LAZY: 1,
};

export const GIRepositoryError = {
  TYPELIB_NOT_FOUND: 0,
  NAMESPACE_MISMATCH: 1,
  NAMESPACE_VERSION_CONFLICT: 2,
  LIBRARY_NOT_FOUND: 3,
};

export const GParamFlags = {
  READABLE: 1 << 0,
  WRITABLE: 1 << 1,
  READWRITE: 3,
  CONSTRUCT: 1 << 2,
  CONSTRUCT_ONLY: 1 << 3,
  LAX_VALIDATION: 1 << 4,
  STATIC_NAME: 1 << 5,
  STATIC_NICK: 1 << 6,
  STATIC_BLURB: 1 << 7,
  EXPLICIT_NOTIFY: 1 << 30,
  DEPRECATED: 1 << 31,
};

export const GConnectFlags = {
  AFTER: 1 << 0,
  SWAPPED: 1 << 1,
};

export const G_TYPE_FUNDAMENTAL_SHIFT = 2;
export const G_TYPE_FUNDAMENTAL_MAX = 255 << G_TYPE_FUNDAMENTAL_SHIFT;

export const GType = {
  INVALID: 0 << G_TYPE_FUNDAMENTAL_SHIFT,
  NONE: 1 << G_TYPE_FUNDAMENTAL_SHIFT,
  INTERFACE: 2 << G_TYPE_FUNDAMENTAL_SHIFT,
  CHAR: 3 << G_TYPE_FUNDAMENTAL_SHIFT,
  UCHAR: 4 << G_TYPE_FUNDAMENTAL_SHIFT,
  BOOLEAN: 5 << G_TYPE_FUNDAMENTAL_SHIFT,
  INT: 6 << G_TYPE_FUNDAMENTAL_SHIFT,
  UINT: 7 << G_TYPE_FUNDAMENTAL_SHIFT,
  LONG: 8 << G_TYPE_FUNDAMENTAL_SHIFT,
  ULONG: 9 << G_TYPE_FUNDAMENTAL_SHIFT,
  INT64: 10 << G_TYPE_FUNDAMENTAL_SHIFT,
  UINT64: 11 << G_TYPE_FUNDAMENTAL_SHIFT,
  ENUM: 12 << G_TYPE_FUNDAMENTAL_SHIFT,
  FLAGS: 13 << G_TYPE_FUNDAMENTAL_SHIFT,
  FLOAT: 14 << G_TYPE_FUNDAMENTAL_SHIFT,
  DOUBLE: 15 << G_TYPE_FUNDAMENTAL_SHIFT,
  STRING: 16 << G_TYPE_FUNDAMENTAL_SHIFT,
  POINTER: 17 << G_TYPE_FUNDAMENTAL_SHIFT,
  BOXED: 18 << G_TYPE_FUNDAMENTAL_SHIFT,
  PARAM: 19 << G_TYPE_FUNDAMENTAL_SHIFT,
  OBJECT: 20 << G_TYPE_FUNDAMENTAL_SHIFT,
  VARIANT: 21 << G_TYPE_FUNDAMENTAL_SHIFT,
};
